name: Build SCSS Variables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate SCSS variables from JSON tokens
        run: npx style-dictionary build --config style-dictionary.config.json

      - name: Check generated SCSS file
        run: |
          # List files in build/scss/ to check if _variables.scss was generated
          ls -la build/scss/

      - name: Commit and push generated SCSS files
        run: |
          # Configure git user for commits
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Check if the _variables.scss file exists before adding it
          if [ -f "build/scss/_variables.scss" ]; then
            # If the file exists, add and commit it
            git add build/scss/_variables.scss
            git commit -m "Override SCSS variables"
            git push
          else
            echo "No changes to _variables.scss, skipping commit."
          fi
